// angular-app/src/app/todo/todo.component.ts
import { Component, Input } from '@angular/core';
import { Todo } from '../todo';
import { TodoService } from '../todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css'],
})
export class TodoComponent {
  @Input() todo!: Todo;

  constructor(private todoService: TodoService) {}

  handleCompleteClick() {
    this.todoService.completeTodo(this.todo.title);
  }

  handleDeleteClick() {
    this.todoService.deleteTodo(this.todo.title);
  }
}

<div>
  <div class="flex mb-4 items-center">
    <p
      [ngClass]="{ 'line-through': todo.completed }"
      class="w-full text-grey-darkest"
    >
      {{ todo.title }}
    </p>
    <button
      (click)="handleCompleteClick()"
      [ngClass]="{
        'hover:bg-green-700': !todo.completed,
        'hover:bg-teal-700': todo.completed
      }"
      class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green-700 border-green"
    >
      {{ todo.completed ? 'Undone' : 'Done' }}
    </button>
    <button
      (click)="handleDeleteClick()"
      class="flex-no-shrink p-2 ml-2 border-2 rounded text-red-700 border-red-700 hover:text-white hover:bg-red-700"
    >
      Remove
    </button>
  </div>
</div>

// svelte-app/src/components/Todo.svelte
<script lang="ts">
  export let todo;
  export let deleteTodo: (title: string) => void;
  export let completeTodo: (title: string) => void;
</script>

<div>
  <div class="flex mb-4 items-center">
    <p
      class="w-full text-grey-darkest {todo.completed ? 'line-through' : ''}"
    >
      {todo.title}
    </p>
    <button
      on:click={() => completeTodo(todo.title)}
      class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green-700 border-green hover:bg-green-700"
    >
      {todo.completed ? 'Undone' : 'Done'}
    </button>
    <button
      on:click={() => deleteTodo(todo.title)}
      class="flex-no-shrink p-2 ml-2 border-2 rounded text-red-700 border-red-700 hover:text-white hover:bg-red-700"
    >
      Remove
    </button>
  </div>
</div>
