// angular-app/src/app/todo-list/todo-list.component.ts
import { Component } from '@angular/core';
import { TodoService } from '../todo.service';

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css'],
})
export class TodoListComponent {
  constructor(public todoService: TodoService) {}
}

<div>
  <h1 class="text-3xl text-grey-700 font-bold my-3">Todo List</h1>
  <div class=" ">
    <app-todo *ngFor="let todo of todoService.todos" [todo]="todo"></app-todo>
  </div>
</div>

// svelte-app/src/components/TodoList.svelte
<script lang="ts">
  export let todos;
  export let deleteTodo: (title: string) => void;
  export let completeTodo: (title: string) => void;

  import Todo from './Todo.svelte';
</script>

<div>
  <h1 class="text-3xl text-grey-700 font-bold my-3">Todo List</h1>
  <div>
    {#each $todos as todo (todo.title)}
      <Todo {todo} {deleteTodo} {completeTodo} />
    {/each}
  </div>
</div>
