// svelte-app/src/components/NewTodo.svelte
<script lang="ts">
  export let createTodo: (todo: { title: string; completed: boolean }) => void;

  let newTitle = '';

  function handleTitleChange(title: string) {
    newTitle = title;
  }

  function handleAddClick() {
    createTodo({
      title: newTitle,
      completed: false,
    });
    newTitle = '';
  }
</script>

<div class="flex my-4">
  <input
    bind:value={newTitle}
    on:input="{(e) => handleTitleChange(e.target.value)}"
    class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker"
    placeholder="Add Todo"
  />
  <button
    on:click={handleAddClick}
    class="flex-no-shrink p-2 border-2 rounded text-teal-700 border-teal hover:text-white hover:bg-teal-700"
  >
    Add
  </button>
</div>

// angular-app/src/app/new-todo/new-todo.component.ts
import { Component } from '@angular/core';
import { TodoService } from '../todo.service';

@Component({
  selector: 'app-new-todo',
  templateUrl: './new-todo.component.html',
  styleUrls: ['./new-todo.component.css'],
})
export class NewTodoComponent {
  newTitle = '';

  constructor(private todoService: TodoService) {}

  handleTitleChange(title: string) {
    this.newTitle = title;
  }

  handleAddClick() {
    this.todoService.createTodo({
      title: this.newTitle,
      completed: false,
    });
    this.newTitle = '';
  }
}

<div class="flex my-4">
  <input
    [(ngModel)]="newTitle"
    class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker"
    placeholder="Add Todo"
  />
  <button
    (click)="handleAddClick()"
    class="flex-no-shrink p-2 border-2 rounded text-teal-700 border-teal hover:text-white hover:bg-teal-700"
  >
    Add
  </button>
</div>
